{
    "type": "bundle",
    "id": "bundle--25ba8f90-aa0f-4f21-a934-a6a6f5af41cd",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--b27041e7-70ef-484b-87e3-ab8c8d6a8f09",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-11-22T00:22:27.719729Z",
            "modified": "2024-11-22T00:22:27.719729Z",
            "name": "CVE-2024-53432",
            "description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-53432"
                }
            ]
        }
    ]
}